# mysql 자체에서 쓸 mysql.yml을 만든거임.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8
          name: mysql
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: initdb
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "auth_system"
  MYSQL_DATABASE_URL: "jdbc:mysql://mysql:3306/auth_system"
  initdb.sql: |
    use auth_system;
    CREATE TABLE employee (id bigint NOT NULL AUTO_INCREMENT, first_name varchar(255) DEFAULT NULL, last_name varchar(255) DEFAULT NULL, department_id bigint DEFAULT NULL, kakao_nick_name varchar(255) DEFAULT NULL, PRIMARY KEY (id));
    INSERT INTO employee (id, first_name, last_name, department_id, kakao_nick_name) VALUES (1, '영웅', '조', 1, '조영웅');
    CREATE TABLE department (id bigint NOT NULL AUTO_INCREMENT, dept_name varchar(255) DEFAULT NULL, team_lead_id bigint DEFAULT NULL, PRIMARY KEY (id));
    INSERT INTO department (id, dept_name, team_lead_id) VALUES (1, '인사팀', 1);